Given "I fill in all the fields" do
  fill_in("First Name", with: "Eliza")
  fill_in("Last Name", with: "Brock")
  fill_in("Phone", with: "1112223333")
  select('June', from: "student_date_of_birth_2i")
  select('6', from: "student_date_of_birth_3i")
  select('1944', from: "student_date_of_birth_1i")
  fill_in("Twitter", with: "@eliza")
  fill_in("Personal URL", with: "www.eliza.com")
  fill_in("Employment History", with: "Robber Baron")
  choose("Self-employed")
  fill_in("Why are you applying for the Nashville Software School?", with: "because")
  fill_in("What is your background with computers/technology/programming?", with: "nada")
  fill_in("student_tech_story", with: "I cannot")
  fill_in("student_site_critique", with: "It's wonderful")
  fill_in("Please tell us something surprising or amusing that you have discovered.", with: "I am a cucumber test")
  fill_in("student_video", with: "www.youtube.com")
  choose("January 2013 for Web Development Bootcamp")
  choose("Yes")
  choose("Yes, if accepted I will need sponsorship in order to attend the summer 2012 program")
  choose("No but I will be moving there to attend Nashville Software School")
  fill_in("student_commitments", with: "I have no commitments")
  fill_in("student_awareness", with: "A little bird told me")
  fill_in("student_anything_else", with: "There is nothing else you need to know")
end
